In [13]:
import torch
a = torch.tensor([1.0, 2.0])

In [15]:
a

tensor([1., 2.], requires_grad=True)

In [8]:
print(a.grad)

None


In [14]:
a.requires_grad=True

In [9]:
a1 = a.requires_grad_(True)

In [10]:
a1

tensor([1., 2.], requires_grad=True)

In [11]:
a

tensor([1., 2.], requires_grad=True)

In [12]:
a.grad

In [16]:
l = a.sum()

In [17]:
l.backward()

In [18]:
a

tensor([1., 2.], requires_grad=True)

In [19]:
a.grad

tensor([1., 1.])

In [20]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### multivariate normal

In [83]:
from scipy.stats import multivariate_normal
a = torch.ones((2))*2
multivariate_normal.pdf(a, a, a, allow_singular=True)

0.07957747154594767

In [88]:
from torch.distributions import MultivariateNormal
a = torch.ones((2)).cuda()*2
cov = torch.diag(a)
dist = MultivariateNormal(a, cov)

In [89]:
torch.exp(dist.log_prob(a)).item()

0.07957746833562851

### under independent assumption

In [90]:
from torch.distributions import Normal
mu = torch.tensor([2,3])
sigma = torch.tensor([0.5, 1])
dist = Normal(mu, sigma)

In [91]:
dist.log_prob(torch.ones((2))).sum(dim=0)
Normal(a,a).log_prob(a).sum(dim=0)

tensor(-3.2242, device='cuda:0')

In [93]:
torch.exp(Normal(a,torch.sqrt(a)).log_prob(a).sum(dim=0)).item()

0.07957746833562851

In [100]:
Normal(a, torch.sqrt(a)).sample()

tensor([-0.5391,  4.1996], device='cuda:0')

In [44]:
a = torch.ones(1)
a.to(device='cpu')

tensor([1.])

In [45]:
a.shape[:-1]

torch.Size([])

In [47]:
torch.tensor(1).shape

torch.Size([])

In [49]:
a.to(int)

tensor([1])

In [53]:
torch.ones((2,3)) * torch.ones((2,3,4))

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 2

In [54]:
2**-0.25

0.8408964152537145

In [61]:
torch.ones((2,3)).clamp(min=0.01)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [63]:
torch.zeros(())**-0.25

tensor(inf)

In [67]:
type(max(0.01, 1))

int

In [68]:
1/torch.tensor([2,3])

tensor([0.5000, 0.3333])

In [102]:
num_accept = 0
num_accept.unsqueeze(-1).expand(-1, -1, x0.shape[-1]).float().clamp(min=eps)

AttributeError: 'int' object has no attribute 'unsqueeze'

In [106]:
torch.tensor([0.5, 0.9, 1.3]).clamp_max(1)

tensor([0.5000, 0.9000, 1.0000])